### ISSUE TITLE
Writing memory issue

### ISSUE THREAD

**Issue by DeathRGH** [xemio/jkpatch#10]
In the latest version the writing memory seems to be broken. I replaced the wrtie memory code in the client with the old and previously working one and still same result. So imo it has something to do with the payload. As an example: I send the write command with byte 0x44 and it actually writes 0x01.

**Comment by jogolden** [comment]
I am currently working on a fix for the whole rpc, linked to issue #9 I have been testing some stuff and the current build is messed up.

**Comment by jogolden** [comment]
Should be all fixed.
