### ISSUE TITLE
rpc stub caller has no sleep and high priority

### ISSUE THREAD

**Issue by jogolden** [xemio/jkpatch#12]
I need to fix the stub caller code to have a sleep inside of it. Right now it will lag the system because the thread steals all the resources. I need to schedule it properly and make sure it sleeps a proper amount of time.

**Comment by DeathRGH** [comment]
I noticed an issue like that while just reading memory. After I read memory a few times, the game gets more and more laggy until it finally shuts down the ps4

**Comment by DeathRGH** [comment]
Just tried to get more information about that and its seems to be an issue if close the application that is connected and then connect it again after re opening the app. If you connect like this 2-3 times the console will either freeze or shut down.

**Comment by jogolden** [comment]
Yes I know, when ever you connect, it creates a new kernel thread and since I currently cannot detect if the thread has exited, it lags. This is all linked to issue #11
