### ISSUE TITLE
Can't boot games with updates applied

### ISSUE THREAD

**Issue by Byrom90** [xemio/jkpatch#18]
Booting games with updates applied while running jkpatch causes a console reboot and check of the file system. Base versions of COD BO3 & IW boot fine but booting COD MWR & AW with updates applied results in the issue described above. All games are fakepkg versions and work fine when using only ps4-hen-vtx and worked previously with 4.05 release of jkpatch. Here's a uart log while booting the MWR game if that helps https://pastebin.com/LZT5CpiK

**Comment by jogolden** [comment]
There are some issues with memory mapping related stuff I believe?
They changed something in the 4.55 kernel and I need to reverse some stuff to figure it out.

Thank you for the debug log!! Very helpful!

**Comment by Talixme** [comment]
Some games like "Prey" doesnt even boot, with and without updates. 4.55 firm

Thanks.

**Comment by vampirexx78** [comment]
Please Golden any news about your update of this amazing plugin please?
