### ISSUE TITLE
Numbers in some games are bugged

### ISSUE THREAD

**Issue by Pretinaverse** [xemio/jkpatch#20]
I activated debug settings using jkpatch, loaded Dragon Quest Heroes (CUSA02769), played the tutorial, then went to a shop and all the money related numbers were bugged!! Just for you to know, i didn't do any editing... i didn't even do any search or anything. So, i saved the game, shut down the console, turned on again, send hen from vtx, loaded the game, and didn't have any problem with the values on screen. I tried shutting down and turning on the console again, sending jkpatch payload, but the number were bugged again.

Here some screenshot of the game loaded with jkpatch and loaded with ps4hen from vtx.

**Jkpatch Screenshot**
![dragon quest heroes_ el infortunio del arbol del mundo y la raiz del mal_20180309013327](https://user-images.githubusercontent.com/28994546/37191351-c2aac47e-233d-11e8-9ac3-246976894014.jpg)

**PS4hen-vtx Screenshot**
![dragon quest heroes_ el infortunio del arbol del mundo y la raiz del mal_20180309013937](https://user-images.githubusercontent.com/28994546/37191360-cbbc4b5a-233d-11e8-9061-7e23555e7c62.jpg)

**Comment by jogolden** [comment]
Did this happen on 4.05?

**Comment by Pretinaverse** [comment]
4.55
I used your latest version of jkpatch.

**Comment by jogolden** [comment]
Yeah, but back then, when you were on 4.05, did this happen?

**Comment by Pretinaverse** [comment]
Sorry, i didn't tried the game back then, so i don't know u.u
