### ISSUE TITLE
ASLR patch not working in 4.55

### ISSUE THREAD

**Issue by Pretinaverse** [xemio/jkpatch#21]
So, i was having problems finding addresses in new games i was playing in 4.55. Sometime i found a value i wanted, but, the next time i wanted to found the same value, i couldn't, and needed several tries before find it again. So, i went to a previously played game, that i have no problem to find values in 4.05. I'm talking about Final Fantasy XV.

In the game i have 545.865.657 of money... and yes, i give me that money in 4.05 using jkpatch with ps4cheater. That's a number very big, so one search is everything i need to found it again. So, i tried now, in 4.55, and this is what i get:

![first scan](https://user-images.githubusercontent.com/28994546/37226488-de91c702-23b8-11e8-891b-7a966bd4c78d.jpg)
This is the first scan i made. You can see i found the value right away. But when i refreshed the address, the value changed to 2147483648. So, i scanned again, and again, and again... and this are my results:

![second scan](https://user-images.githubusercontent.com/28994546/37226541-0e6101f0-23b9-11e8-973d-bb3e25daeceb.jpg)
You see? After every search, the address change 4 hex forward, i don't know why...

**Comment by jogolden** [comment]
That might just be how the game is? ASLR only effects the binaries not the HEAP and the name of that memory region literally has HEAP in it.

**Comment by Pretinaverse** [comment]
That didn't happen in 4.05. That's why i checked before posting an issue. I understand if the addresses change after reseting the game. But without closing it, is weird this happens.

This happens to me with Horizon Zero Dawn as well. And now i tested Tales of Zestiria. The address of the value changes in less than 20 seconds. And if you try to poke a new value, the address change right away after the poke. Is like, any change in memory provoke a change in the addresses location. Obviously this didn't happen to me back in 4.05.

**Comment by jogolden** [comment]
I have no clue what the problem is then... if the address truly changes or it is something with PS4Cheater? I mean for the address to change there would have to be some serious problems to change the PTE in the kernel. Which there are some serious problems with jkpatch lmao

**Comment by Pretinaverse** [comment]
I wonder if it is possible for ps4cheater to temporarily activate the aslr every time a search or a refresh is performed and therefore the addresses change. I kept doing tests and searched a big value with ps4cheater so I could find it on the first try. I wrote down the address, closed the game and reopened it. This time I didn't use ps4cheater, but went straight to memview. I wrote down the address I had obtained before, peek and immediately found the value I had found before. I poked a new value and everything worked perfectly. I made a new peek and the addresses hadn't changed. Apparently, the ps4cheater search system is the one that alters the game memory, activating the aslr temporarily with each search. In fact, I tried to look for a value with ps4cheater and then went to memview and the values in the direction I was looking changed completely after making a peek. But i don´t understad how ps4cheater can activate the aslr if jkpatch is blocking it...

**Comment by Pretinaverse** [comment]
So, in the end, aslr patch is working... the problem is, some programs can overwrite this and activate aslr like ps4cheater does when it refresh the values in the found addresses that are added at the bottom part of the tool. Wen the saved addresses are refreshed, aslr is activated for a moment, but that is enough to alter the entire memory. The problem is, if you have multiple addresses saved in ps4cheater, if you change one value, the other are refreshed automatically after the change is made. And, even if you have only one address saved in ps4cheater, everytime you perform a search, the search itself alter the memory. If you don't have any saved address, you can search without altering the memory, or so it seem (for what i could see after multiples tests).

So, the real question will be:
**_Is there something you can do to prevent other programs like ps4cheater to activate aslr even though you had blocked it with jkpatch?_**

If not, then, the only solution will be to talk with the chinese developer to fix his program... but even though i registered in the forum, i need to verify my CHINESE phone number to post... and obviously, i don't have a chinese phone number u.u

**Comment by jogolden** [comment]
You would have to contact the creator of PS4Cheater. Latley I have not had the time or commitment to update jkpatch, please give it time. I don't think many people are interested in it anyway.

**Comment by Pretinaverse** [comment]
Well, for now you can forget about this issue. The chinese developer opened a github page and updated his ps4cheater. The problem with the memory is now fixed. I just tested with all the games i said i have problems before, and all works great ;)

I hope you can keep working in jkpatch making it better and better ;)
