### ISSUE TITLE
nioh auto rebooting 4.55

### ISSUE THREAD

**Issue by agungsetiawan23** [xemio/jkpatch#23]
there is a bug, when the payload injecting, and wanna go to the main menu in game, my ps4 just rebooting for some reason, idk know why, hope fix it soon, thanks!

**Comment by Talixme** [comment]
The problem is that the payload on 4.55 overwrite memory parts in some games. Hopely will be fix soon, hurrican6 keep working very hard on the PS4Cheater soft but for the people that have updated to 4.55 we will have to wait for a update to fix this problem.

**Comment by agungsetiawan23** [comment]
its happening to on memoryview, not just on ps4 cheater

**Comment by Pretinaverse** [comment]
Because that's not a problem with ps4cheater or memview... is a problem with the payload and some games with updates. Nioh is an updated game so, it have some incompatibilities right now with jkpatch. But it seems not all games have this issue? I updated HZD to 1.22 and i'm still able to play it using jkpatch xD

**Comment by agungsetiawan23** [comment]
my NIOH just v 1.00, im not update anything,
yo i try it on tales of berseria and its same result, but some games like watchdogs 2, and nier there is no problem with the payload.
oh can u give me tutorial how to update game? i see modded warfare but it just for original game (Disc) not fpkg.
sorry for off-topic.

**Comment by Pretinaverse** [comment]
If you downloaded Nioh from psxhax, then the game was already updated.
And updates are installed like any other pkg ;)

**Comment by agungsetiawan23** [comment]
so what can i do about that?
where can i download the game without update?

**Comment by Pretinaverse** [comment]
The only thing you can do, is wait until jkpatch gets fixed.

**Comment by Myoko** [comment]
uncharted 4 auto rebooting too on 4.55 with loading save please fix it.

**Comment by Pretinaverse** [comment]
Crap. It happened to me!!!
It was with Hitman [CUSA06535] v.1.00 with **NO** updates.
Opened the game and get a kernel panic. The console reboots and checked the hard drive. I tried again just in case and....... dejavu. It seems i won't be able to use ps4cheater with this game for the time being.

**Comment by iiHawe** [comment]
@Pretinaverse How about injecting the payload after starting the game? I'm working on TLUO for a while and never had any issues with PS4Cheater.
