### ISSUE TITLE
Some addresses become hidden?

### ISSUE THREAD

**Issue by Pretinaverse** [xemio/jkpatch#24]
This is just a question, so you can label it as that. Because i don't know if this is a problem with jkpatch or something else. In fact, i posted this same issue in the ps4cheater git just in case.

This is a problem i only have with Horizon Zero Dawn. I don't know if it happens in other games. And i only tested this with ps4cheater. I can't tested it with the ps4 trainer utility of zerofox, because he hasn't added yet a search option for unknown initial value u.u

Let me explain (and maybe you can try yourself if you have the game)

I was trying to find health in horizon zero dawn. I tried **float**, 2 bytes, 4 bytes, but nothing.
Then i did a 4 byte search, using unknown initial value, and then, did several next scan using only changed and unchanged value. At the end, i had 8 addresses. No matter how much i changed my health in game, those 8 addresses were always there. So, those addresses have something to do with health? That is what i thougth. I tried marking the first one, fall from a high altitud... but my hp went down. I tried the second one, the third one, and so on, but my hp always went down. And then, i tried marking all of them at the same time. And it work!! My hp didn't went down anymore. I did more testing and, at the end, only two of the 8 addresses are needed to be locked to freeze health.

![6o9xw15](https://user-images.githubusercontent.com/28994546/37614338-4b78339c-2b89-11e8-823d-eb0427b5a132.jpg)

So, here is the problem, or several problems. Or maybe, this is only one big problem.
The health is frozen and everything works fine until i teleport to another campfire. If i teleport, the stored codes stop working and my health stops being frozen. In this case 3 things can happen.

- The first is that if I close ps4cheater, open it again and load the saved codes, my health freezes up again and everything continues to function normally.

- The second is that the codes stop working even if I restart ps4cheater. And even if I look for the codes again and find them, the addresses has not changed and they still don't work when locked.

- And the third is that, even if I search for the addresses using the same method mentioned above, I can't find them again, no matter how much I search. It's like they've been hiding. And when this happens, two more things can happen:

1. The first is that I simply can't find the health address again, unless I restart the game.

2. And the second is that **it becomes possible to find health by searching with float and exact value options**.

So, i don't know why this happens. ASLR is locked by jkpatch, so why the addresses suddenly can't be found? And why sometimes i can **find the health as a float value and other times i can't**?
Can be  a problem with aslr? Or maybe the game has some internal system of randomization aside from the aslr of the ps4? Or it has something to do with the search method?

If the health sometimes is hidden in horizon zero dawn, **is possible that there are addresses in other games hidden as well?**. Like when i tried to find the experience points in Star Ocean 5. No matter what type of search i did, i wasn't able to find it. But when i searched the exp needed to level up (instead of the accumulated exp until now), i find that right away.

**Comment by jogolden** [comment]
ALSR only applied to the main executable, meaning the static text/data sections of the SELF.
I don't think this is an issue with either tool, just the way Horizon seems to work. Same with Star Ocean 5, that is just how the developers programmed the game.

Wait until we have debugging and you can find out what accesses those memory positions and then reverse engineer the actual game.

**Comment by Pretinaverse** [comment]
I did more testing. In the end, the real reason for what sometimes i was unable to find my health, was the search funtion of ps4cheater and ps4 trainer utility, because sometimes, the value was fractioned and while i was looking for, let say, 495, the real value was 494,1367.

The address of health keep changing after i died, though, but as you say, this has to be how the game works. So, i'm closing this issue, and thanks for taking the time to answering me ;)
