### ISSUE TITLE
jkpatch 5.05 not work

### ISSUE THREAD

**Issue by Myoko** [xemio/jkpatch#27]
jkpatch 5.05 not work, when send payloads ps4 power down

**Comment by MozzieMD** [comment]
yeah, same story

**Comment by Leeful** [comment]
Same problem here. 
payload.bin sends fine but when kpayload.elf is sent it causes a kernel panic /shutdown.

**Comment by EROOTIIK** [comment]
same but the jkpatch from withmetta is working for 5.05
