### ISSUE TITLE
Random Shut Down with RPC Client

### ISSUE THREAD

**Issue by DeathRGH** [xemio/jkpatch#6]
The payload seems to crash when your refreshing processes too often. Not in a short ammount of time just in general. When I reload my tool it sometime just shuts down my console when I first grab the process list.

Also shuts down sometimes when peeking memory, even if its just 0x100 in lenght.

**Comment by jogolden** [comment]
Yeah I believe this was due to a race condition in disable_copy_checks() vs enable_copy_checks(). Where cr0 would be set, then unset, but writing was taking place so it would fault. I have fixed this in latest issue.
