### ISSUE TITLE
[jkpatch] install_payload: load_elf failed (r: 1)!

### ISSUE THREAD

**Issue by Mistawes** [xemio/jkpatch#8]
Hi there,

First, I'd like to say thanks for this great tool!

However, I can't seem to get this to build properly. I don't get any errors in output when compiling. But when I fire over the payload, followed by the elf, I get the following. (I can use your elf from the release page, with my payload.bin and it works fine) - Just curious if you've seen it before. I'm currently checking LLVM etc. Thanks!

jkpatch installer loaded
[jkpatch] kernbase 0xFFFFFFFF8B788000
[jkpatch] loading payload...
[jkpatch] install_payload: load_elf failed (r: 1)!
[jkpatch] install_payload failed!

**Comment by jogolden** [comment]
Try writing some more printf's in the code trace back exactly where it returns 1.

**Comment by Mistawes** [comment]
Just a note, that I finally found a workaround.. One FreeBSD VM later, multiple custom builds of binutils etc..

It came down to this check (elf.c-line:9):
```
// only support relocatable elfs rn lol
if (ehdr->e_type != ET_REL && ehdr->e_type != ET_DYN) {
	return LDR_INVALID_ELF;
}
```

I just needed to modify the header of the elf:
elfedit --output-type=DYN kpayload.elf
